### ISSUE TITLE
Handle Streaming RPC calls between Cluster Nodes

### ISSUE THREAD

**Issue by KhaledEmaraDev** [DibiBase/dibibase#7]
# gRPC
* gRPC is a fast and efficient binary RPC protocol. it was built on top of HTTP/2.0 to avoid head-of-line blocking problems and to ensure headers compression.
* gRPC uses protocol buffers as its Interface Definition Language (IDL) and as its underlying message interchange.
* Both gRPC and protocol buffers are open source projects and maintained by Google.

## Modes of operation

* ### Unary RPC
  It's similar to traditional HTTP requests.
  * The client calls the stub method.
  * The server is notified that the RPC has been invoked with the client’s metadata for this call.
  * The server process the client’s request message then creates a response. 
  * The response is then returned to the client together with status details
 
* ### Server streaming RPC
   It's similar to a unary RPC except that the server returns a stream of messages.
   The server sends all the messages then a status code to complete the processing on the server-side.
   The processing on the client-side is finished once it receives all the messages from the server.

* ### Client streaming RPC
   It's similar to server streaming RPC except that the client is the one who is sending a stream of messages.

* ### Bidirectional streaming RPC
   The call is initiated by the client invoking the method and the server receiving the client metadata.
     It's a combination of Server and Client streaming.
   The client and server can read and write messages in any order.

## Channels
gRPC channels provide a connection to a gRPC server on a specified host and port. It is used when creating a client stub. Clients can specify channel arguments to modify gRPC’s default behavior, such as message compression. A channel has a state including connected, and idle.

**Comment by hassanelshazly** [comment]
Prototype Done
